name: ETMOC Scraper

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup uv
        uses: astral-sh/setup-uv@v1

      - name: Install system dependencies for Playwright
        uses: microsoft/playwright-github-action@v1
        with:
          install-deps: true

      - name: Install Python dependencies with uv
        run: |
          uv pip install -r requirements.txt

      - name: Install Playwright Browsers (via uv)
        run: |
          uv run playwright install

      - name: Run scraper (catalog detail, 1 page) via uv
        run: |
          uv run python playwright_scrape_etmoc.py --source catalog --action detail --pages 1 --out etmoc_output

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: etmoc_output
          path: etmoc_output